### ISSUE TITLE
Pypi release?

### ISSUE THREAD

**Issue by Deer-Spangle** [StormyDragon/python-flist#8]
Hey there!

This looks realy handy for a lil project I wanna work on, but I can't find a pypi release for it. The setup.py made me think one exists, but my searching hasn't worked.

Is this lib available on pypi? could it be published there if not?

**Comment by StormyDragon** [comment]
Gosh, it's been a while since I worked on this thing, but no I never did make a release for it.
I think pip or poetry will allow you to install directly from the github repo

```
pip install git+https://github.com/StormyDragon/python-flist
poetry add git+https://github.com/StormyDragon/python-flist
```

**Comment by Deer-Spangle** [comment]
Heh, that's fair enough! I spotted it in your account and 👀 
It's relevant to some projects I've been considering on-and-off.

But yeah, fair enough, I can install from git. It just looked like there might be a pypi package somewhere, given the versioning and such. Thanks!
